version: '3.8'
services:
  back:
    build:
      context: ./
      dockerfile: dockerfile_back
    depends_on:
      - db
    command:
        - /bin/sh
        - -c
        - |
          alembic upgrade head
          uvicorn DoItList.main:app --host 0.0.0.0 --port 8080
    ports:
      - '8080:8080'
  front:
    build:
      context: ./
      dockerfile: dockerfile_front
    ports:
      - "3000:3000"
    volumes:
      - "/do-it-list-front/node_modules"
      - "./do-it-list-front:/do-it-list-front"
    working_dir: /do-it-list-front
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    ports:
      - '5452:5432'
    volumes:
      - ./pg:/var/lib/postgresql/data
